### ISSUE TITLE
Hash rom file before starting emulator

### ISSUE THREAD

**Issue by ReenigneArcher** [LizardByte/RetroArcher-plex#50]
If hard drive isn't spun up desktop of server will show on Moonlight client briefly before emulator is started.

Rom path is found in this line:
https://github.com/ReenigneArcher/RetroArcher.bundle/blob/5a356ad8cdaaa15ffed7355d41f15848d003e54c/Contents/Code/retroarcher/retroarcher.py#L311

Emulator starts in this line:
https://github.com/ReenigneArcher/RetroArcher.bundle/blob/5a356ad8cdaaa15ffed7355d41f15848d003e54c/Contents/Code/retroarcher/retroarcher.py#L363

Should hash the file after L311 to initiate a hard drive spin up and locate the file. A partial hash should be sufficient.

**Comment by ReenigneArcher** [comment]
Hashing the file takes a long time on larger iso games... maybe not the best option.

**Comment by 13steinj** [comment]
This should probably be cleaned up in general to use `subprocess` and safer command parsing

**Comment by ReenigneArcher** [comment]
> 
> 
> This should probably be cleaned up in general to use `subprocess` and safer command parsing

Can you provide an example of what should use `subprocess` ?

**Comment by 13steinj** [comment]
> Can you provide an example of what should use `subprocess` ?

`os.system` calls can be replaced (and should be, as it's more standardized in terms of getting data in and out from the running process, as well as asynchronous / synchronous completion) functions / classes in the `subprocess` standard library module (which, depend on the use cases)

**Comment by ReenigneArcher** [comment]
RetroArcher.X will resolve this issue. Will likely add an option to cache games in a specified location that the user can define on an SSD (or wherever they like).
