### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by ReenigneArcher** [LizardByte/RetroArcher-plex#51]
- Add requirements.txt
- Modify readme so users know how to install the requirements
- Remove modules from `\Contents\Libraries\Modules` ... remove entire folder
- Remove `sys.path.append(paths['retroarcherModulesDir'])` from retroarcher.py
- Probably can also remove `sys.path.append(paths['agentModulesDir'])` from retroarcher.py

**Comment by peterHoburg** [comment]
I can take this one.

**Comment by ReenigneArcher** [comment]
> 
> 
> I can take this one.

Okay great! Note this is only for `retroarcher.py`. Nothing that runs inside Plex can use a requirements.txt and those modules need to be included in a folder.

**Comment by ReenigneArcher** [comment]
This will not be necessary with RetroArcher.X; therefore this is being closed.
