### ISSUE TITLE
Create webserver that runs on game streaming server

### ISSUE THREAD

**Issue by ReenigneArcher** [LizardByte/RetroArcher-plex#54]
A webserver running on the game streaming server could significantly improve the user experience.

Functions of the webserver:
- Have a webpage for linking moonlight client devices to the server (if using Sunshine)
- Provide a method to authenticate PC users and write the information to the `secrets.json` file.
  -  Should have a function to verify provided credentials are correct.

**Comment by 13steinj** [comment]
Probably better to implement via Kitana in some way if possible.

https://github.com/pannal/Kitana

**Comment by ReenigneArcher** [comment]
@13steinj the problem is the settings in the agent are getting extremely long. I think there are 200+ settings already. We really need a webserver running that will help users manage everything for retroarch.
