### ISSUE TITLE
remove debugging requirement

### ISSUE THREAD

**Issue by Junkbite** [LizardByte/RetroArcher-plex#74]
I have to enable wireless and network debugging for this to work? what's the point? completely cripple my wireless just to be able to have a slightly easier way to play games? no thanks.

**Comment by ReenigneArcher** [comment]
How does this "cripple your wireless"? How else do you expect me to interact with your device?

RetroArcher doesn't send thousands of commands to your device, just a single command when you want to play a game. You can also use MacroDroid or probably tasker to enable wireless debugging only when the Plex app is open.

**Comment by ljmerza** [comment]
Enabling debugging adds logs for all packets. There's a reason why it's disabled and only for debugging. Slows down wireless a lot. Super disappointed after all this time all the hacks you have to do to even get this working.

**Comment by Junkbite** [comment]
enabling debugging makes android log all packets which slows down your wireless big time. pretty disappointed after all this time you release something requiring all these hacks just to get working. hard pass.

**Comment by ReenigneArcher** [comment]
Again, using the Macrodroid solution, which is in the Wiki, will only enable wireless debugging when Plex is open. As soon as Plex is not the foreground app, wireless debugging is disabled again. I have this working on Nvidia Shield TV, 2 Bravia TVs, and a Pixel 3 and haven't noticed any decrease in network performance. You're welcome to develop a better solution if you like, though. Have a nice day.
